### ISSUE TITLE
Refresh content on Portal

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/Community#172]
Need to refresh the content on the portal. Possibly tweaking layout a little bit.

Possible new content includes:
- [ ] Science articles relevant to MAAP, obtained from project scientists
- [ ] Sample news entries highlighting new features in MAAP
- [ ] Introductory tutorial on how to use the portal

**Comment by marjo-luc** [comment]
@gchang Is there a place I can pull these articles from? If not, can you recommend folks I should contact?

**Comment by gchang** [comment]
Previous tix to consider #239
