### ISSUE TITLE
Missing License file on Repositories

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/Community#544]
**Describe the bug**
Public repositories do not have the appropriate open source license file.

**To Reproduce**
Go to any of the repositories (public or private) under the MAAP-Project organization (that is not a fork from another org), the license file is either:
1. Missing
2. Missing the correct Copyright, [example](https://github.com/MAAP-Project/user-management-jupyter-extension/blob/b24b21fcd6ac4efbc9ab8681604c886a0989090a/LICENSE#L189) - No copyright owner is specified.

**Expected behavior**
Every repository that originates with the MAAP-Project should be under the Apache 2.0 License (as approved by JPL and NASA)

**Additional context**
Using the Github API we can check the License status (1)
https://api.github.com/orgs/maap-project/repos returns contain a license item for each repo.
The API may show only public repos without authentication, however we should probably apply the license to all repos that contain original work by the MAAP teams.

Q: Apache 2.0 has the option to move the Copyright portion into a NOTICE file https://infra.apache.org/licensing-howto.html, this is only required if your code includes any dependencies where you need to maintain the copyright notice, and that might be under a different but compatible license. Should we create NOTICE files for everything or only as needed when included dependencies?

**Tasks**
- [x] Agree to a Copyright line: @gchang @kbugbee1 do you have examples of prior software or docs showing what the copyright string should say?
    - [ ] Should all repos get joint copyright between organizations, or only be assigned to the orgs that contribute to the code? 
- [ ] Apply to all repositories in the organization.
- [ ] Update existing license files to include correct Copyright

**Comment by wildintellect** [comment]
Examples:
"Copyright 2018 California Institute of Technology.  Government Sponsorship Acknowledged." https://github.com/nasa-jpl/open-source-rover/blob/master/LICENSE.txt

"United States Government as represented by the Administrator of the National Aeronautics and Space Administration. All rights reserved."
https://github.com/nasa/openmct/blob/master/LICENSE.md

More examples can be found in https://code.nasa.gov/#/ but I haven't found a particularly good one yet.

**Comment by wildintellect** [comment]
We can also check the "Community Standards" page (under insights) of each repo to assess what else needs doing example: https://github.com/MAAP-Project/maap-documentation/community

This will check for contributor agreements, readme, project descriptions, etc... don't see this in the API yet.

**Comment by wildintellect** [comment]
Looking over Apache Foundation examples, copying the default Apache 2 license and adding a NOTICE file with the correct copyright should solve.

**Comment by wildintellect** [comment]
Notes in https://docs.google.com/document/d/17d3cD7BjR3febmhIi4wdSejHnky2yBMJXiPLPw5KS-w/edit

**Comment by marjo-luc** [comment]
The LICENSE, along with other boilerplate documentation, was created and may be found in the template repo here:
https://github.com/MAAP-Project/maap-repo-template/tree/main

It looks like most of the platform team's repos have the latest LICENSE, though some need the copyright year updated. I can create PR's with the latest LICENSE for the remaining repos.

Ticket that captured the work on this documentation: [#667](https://app.zenhub.com/workspaces/maap-platform-5ee7f0d1f440de0024cd359b/issues/gh/maap-project/community/667)

**Comment by gchang** [comment]
Done for NASA repo.
